import { defineConfig } from "tsup"

export default defineConfig({
  clean: true,
  dts: true,

  entry: {
    "auth/authActions": "src/auth/authActions.ts",
    "auth/authCallbacks": "src/auth/authCallbacks.ts",
    "auth/authGate": "src/auth/authGate.ts",
    "auth/authStore": "src/auth/authStore.ts",
    "cache/cacheTtl": "src/cache/cacheTtl.ts",
    "client/createClient": "src/client/createClient.ts",
    "functions/edgeFunctions": "src/functions/edgeFunctions.ts",
    "hooks/index": "src/hooks/index.ts",
    index: "src/index.ts",
    "lifecycle/appLifecycle": "src/lifecycle/appLifecycle.ts",
    "mutation/conflictAudit": "src/mutation/conflictAudit.ts",
    "persistence/encryptedAdapter": "src/persistence/encryptedAdapter.ts",
    "persistence/persistenceAdapter": "src/persistence/persistenceAdapter.ts",
    "persistence/schemaVersion": "src/persistence/schemaVersion.ts",
    "persistence/storageQuota": "src/persistence/storageQuota.ts",
    "query/filters": "src/query/filters.ts",
    "query/pagination": "src/query/pagination.ts",
    "query/queryBuilder": "src/query/queryBuilder.ts",
    "realtime/realtimeManager": "src/realtime/realtimeManager.ts",
    "rpc/rpcAction": "src/rpc/rpcAction.ts",
    "server/prefetch": "src/server/prefetch.ts",
    "storage/storageActions": "src/storage/storageActions.ts",
    "sync/backgroundSync": "src/sync/backgroundSync.ts",
    "sync/crossTabSync": "src/sync/crossTabSync.ts",
    "sync/incrementalSync": "src/sync/incrementalSync.ts",
    "sync/multiDeviceSync": "src/sync/multiDeviceSync.ts",
    "sync/selectiveSync": "src/sync/selectiveSync.ts",
    "sync/syncMetrics": "src/sync/syncMetrics.ts",
  },

  external: [
    "zustand",
    "zustand/middleware",
    "zustand/shallow",
    "zustand/react/shallow",
    "zustand/vanilla",
    "@supabase/supabase-js",
    "react",
    "immer",
  ],

  format: ["esm", "cjs"],
  sourcemap: true,
  splitting: true,
})
